-- liquibase formatted sql changeLogId:8f11c9b6-3071-4e16-9a8e-ac95085200d7
--changeset Davide.Moraschi:20220427_1 labels:batch-tracker-dream context:sandbox dbms:postgresql runAlways:false runOnChange:true runInTransaction:true failOnError:true created:2022-04-27  endDelimiter://
create table if not exists public.batches_old
(
    revised_due_date                               date,
    is_purchase_order                              boolean    default false,
    inputs_planned_start                           date,
    dispo_actual_start                             date,
    test_progress                                  progress,
    mfg_brr_estimated_finish                       date,
    purchase_order_line_no                         integer,
    need_by_updated_by_user_id                     integer,
    mfg_brr_machine_estimated_finish               date,
    material_id_desc                               text,
    ship_actual_start                              date,
    dispo_notes_2                                  text,
    source_progress                                progress,
    orig_dispo_planned_start                       date,
    dispo_notes_3                                  text,
    dispo_notes_1                                  text,
    full_ud_code                                   text,
    requirement_date                               date,
    mfg_planned_finish                             date,
    ship_estimated_finish                          date,
    dispo_active_finish_revised_due_date_diff_days integer,
    id                                             uuid       default uuid_generate_v4(),
    external_sample_actual_start                   date,
    market_segment_description                     text,
    external_test_planned_start                    date,
    mfg_brr_planned_start                          date,
    tests_percent_approved                         integer    default 0,
    ready_for_release                              boolean    default false,
    test_actual_finish                             date,
    auto_move_dispo_and_queue                      boolean    default false,
    mfg_actual_finish                              date,
    qa_brr_planned_start                           date,
    full_mrp_controller                            text,
    risk_status_revised_due_date                   risk_status,
    priority                                       integer,
    deleted_at                                     timestamp with time zone,
    longest_tag_length                             integer    default 0,
    ship_risk_status                               risk_status,
    dispo_planned_start                            date,
    test_estimated_finish                          date,
    dispo_estimated_finish                         date,
    comments_count                                 integer    default 0,
    sample_estimated_start                         date,
    sample_planned_start                           date,
    ship_actual_finish                             date,
    dispo_estimated_start                          date,
    source_risk_status                             risk_status,
    mfg_brr_actual_start                           date,
    out_of_stock                                   date,
    batch_number                                   varchar(20),
    queued_for_sap_export_by_user_id               integer,
    qa_brr_machine_estimated_finish                date,
    detailed_test_status_flag                      text       default 'N'::text,
    sample_planned_finish                          date,
    ship_planned_finish                            date,
    created_at                                     timestamp with time zone,
    mfg_brr_risk_status                            risk_status,
    unreleased_inputs_flag                         text,
    batch_number_or_purchase_order_id              text       default ''::text,
    inputs_risk_status                             risk_status,
    goods_receipt_proc_time                        numeric,
    source_planned_finish                          date,
    updated_at                                     timestamp with time zone,
    qty_issued                                     numeric,
    dispo_actual_finish                            date,
    mfg_progress                                   progress,
    source_actual_finish                           date,
    sample_estimated_finish                        date,
    inputs_estimated_finish                        date,
    external_test_risk_status                      risk_status,
    qa_brr_actual_start                            date,
    dispo_planned_finish                           date,
    test_actual_start                              date,
    external_test_actual_start                     date,
    sample_progress                                progress,
    qa_brr_planned_finish                          date,
    qa_brr_risk_status                             risk_status,
    sample_risk_status                             risk_status,
    lot_cancelled                                  boolean,
    dispo_machine_estimated_finish                 date,
    external_sample_estimated_start                date,
    mfg_estimated_start                            date,
    material_id                                    varchar(4),
    inputs_actual_finish                           date,
    insp_start_date                                date,
    custom_flag                                    text,
    source_planned_start                           date,
    ship_progress                                  progress,
    full_material_code_sap                         text,
    insp_type_description                          text,
    external_test_estimated_start                  date,
    sample_actual_finish                           date,
    auto_queue_if_applicable                       boolean    default false,
    purchase_order_id                              text,
    batch_status                                   text,
    qa_brr_actual_finish                           date,
    external_test_progress                         progress,
    expiration_date                                date,
    source_estimated_finish                        date,
    statistical_delivery_date                      date,
    date_of_mfg                                    date,
    inputs_estimated_start                         date,
    test_risk_status                               risk_status,
    proc_order_status                              text,
    need_by_updated_at                             date,
    test_planned_start                             date,
    average_inspection_duration                    numeric,
    latest_date                                    date,
    queued_for_sap_export_at                       timestamp with time zone,
    mrp_controller_desc                            text,
    date_order_released                            date,
    days_of_supply                                 numeric,
    ship_planned_start                             date,
    earliest_date                                  date,
    external_sample_estimated_finish               date,
    queueable_for_sap_export                       boolean    default false,
    material_code_sap                              varchar(20),
    dispo_risk_status                              risk_status,
    need_by                                        date,
    inputs_actual_start                            date,
    source_estimated_start                         date,
    insp_lot_no                                    varchar(40),
    external_sample_actual_finish                  date,
    vendor_name                                    text,
    external_test_estimated_finish                 date,
    mrp_controller                                 text,
    test_machine_estimated_finish                  date,
    process_order_number                           text,
    qa_brr_progress                                progress,
    lot_hold_flag                                  text,
    test_estimated_start                           date,
    purchasing_group                               text,
    mfg_brr_estimated_start                        date,
    production_scheduler                           text,
    name                                           varchar(255),
    old_id                                         text,
    vendor_batch_number                            text,
    ud_code_description                            text,
    qa_brr_estimated_finish                        date,
    mfg_planned_start                              date,
    qa_brr_estimated_start                         date,
    mfg_estimated_finish                           date,
    full_market_segment                            text,
    market_segment                                 text,
    external_test_actual_finish                    date,
    qty_shipped                                    numeric,
    test_planned_finish                            date,
    mfg_brr_actual_finish                          date,
    inputs_planned_finish                          date,
    inventory_status                               text,
    sample_machine_estimated_finish                date,
    queued_for_sap_export                          boolean    default false,
    lot_hold_details                               text,
    external_sample_planned_start                  date,
    source_actual_start                            date,
    material_category                              text,
    dispo_progress                                 progress,
    disable_auto_updates                           boolean    default false,
    ship_estimated_start                           date,
    insp_type                                      text,
    mpg_code_desc                                  varchar(75),
    plant_code                                     varchar(6) default ''::character varying,
    ud_code                                        varchar(16),
    full_insp_type                                 text,
    external_sample_progress                       progress,
    external_sample_risk_status                    risk_status,
    inputs_progress                                progress,
    mfg_brr_planned_finish                         date,
    dispo_start_estimate_offset                    integer    default 0,
    quantity_delivered                             numeric,
    sample_actual_start                            date,
    due_date                                       date,
    market_code                                    text,
    active_due_date                                date,
    record_type                                    text,
    mfg_actual_start                               date,
    target_quantity                                numeric,
    mfg_risk_status                                risk_status,
    priority_manufacturing_at_risk                 date,
    mfg_brr_progress                               progress,
    external_sample_planned_finish                 date,
    risk_status_due_date                           risk_status,
    external_test_planned_finish                   date
);

